openapi: "3.0.0"
info:
  title: "Event service"
  description: "This service encapsulates Event domain service"
  version: "1.0.0"
  contact:
    email: "echaveen@gmail.com"
servers: 
  - url: "http://{hostname}/{versionId}/api"
    variables:
      hostname: 
        description: "Hostname of the service"
        default: "localhost"
      versionId:
        description: "API version Id"
        default: "v1"
paths:
  /events:
    put:
      summary: "Adds a new Event"
      operationId: "createEvent"
      requestBody:
        description: "new Event"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        400:
          description: "Validation exception"
        201:
          description: "Successful"
  /events/search:
    post:
      summary: "Search Event by criteria"
      operationId: "searchEvent"
      requestBody:
        description: "Search criteria of the Event"
        content:
          application/json:
            schema:
              type: "object"
              title: "SearchCriteria"
              description: "Search criteria"
              properties:
                createdAt: 
                  description: "Creation Timestamp"
                  type: "string"
                  format: "date-time"
                email: 
                  description: "Email address"
                  type: "string"
                  format: "email"
                environment: 
                  description: "Environment name"
                  type: "string"
                component: 
                  description: "Component name"
                  type: "string"
                message: 
                  description: "Partial message"
                  type: "string"
      responses:
        400:
          description: "Validation Exception"
        200:
          description: "Successful"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: "object"
      required: 
        - createdAt
        - email
        - environment
        - component
        - message
        - data
      properties:
        id: 
          description: "Event Id"
          type: "string"
          format: "uuid"
        createdAt: 
          description: "Creation Timestamp"
          type: "string"
          format: "date-time"
        email: 
          description: "Email address"
          type: "string"
          format: "email"
        environment: 
          description: "Environment name"
          type: "string"
        component: 
          description: "Component name"
          type: "string"
        message: 
          description: "Event message"
          type: "string"
        data: 
          description: "Event data"
          type: "string"
